### ISSUE TITLE
SVG Image doesn't use given y position

### ISSUE THREAD

**Issue by cseifert** [meyfa/php-svg#115]
Hi meyfa,

I very much like your great library and it is in heavy use. Updating an project and so the version of the composer package of this library I experienced a strange behaviour. I generate a SVG out of Rectangles, Lines and even images and I use the following code, to add an image to the SVG:

`$document->addChild(
            (new \SVG\Nodes\Embedded\SVGImage(
                $url,
                $x,
                $y,
                10,
                10
            ))
                ->setStyle('fill', '#fff')
                ->setStyle('stroke', '#000')
                ->setStyle('stroke-width', '2px')
        );
`
At the moment I can enter whatever value I want as $y. The image keeps sticky to the same position. That occured using the version 0.11.0 and it doesn't occure if I downgrade to 0.10.0.

Best regards,
Christian

**Comment by meyfa** [comment]
It happens when rasterizing using this same library, right? (vs. outputting as SVG)

Does $x influence the y position?

**Comment by cseifert** [comment]
yes, I'm rastering the SVG as PNG having an SVGImage placed into it. Changing $x works as exepcted, but updating $y doesn't have any effect and the image remains at the same old fixed position.

**Comment by meyfa** [comment]
I've traced it to this line:

https://github.com/meyfa/php-svg/blob/master/src/Rasterization/Renderers/ImageRenderer.php#L28

... which is a simple copy-and-paste error. I would expect increasing $x to also move the image on the y axis, though.

Drafting a fix now.

**Comment by meyfa** [comment]
Just to be sure: Could you temporarily change your PHP-SVG version in Composer to `dev-master` and see if everything works as expected now? If this fixed it, I'll push a patch release.

**Comment by cseifert** [comment]
thanks, that works fine now.

**Comment by meyfa** [comment]
Great! I pushed a new release as v0.11.1. By the way, thanks for your bug report!

**Comment by cseifert** [comment]
The new tag works great. Thank you.
