### ISSUE TITLE
PHP fatal error when loading svg string

### ISSUE THREAD

**Issue by roipoussiere** [meyfa/php-svg#123]
I try to run the code sample [provided in the readme](https://github.com/meyfa/php-svg#loading-an-svg) that loads an svg string:

```php
<?php

require 'vendor/autoload.php';
use SVG\SVG;

$svg  = '<svg width="100" height="100">';
$svg .= '<rect width="50" height="50" fill="#00F" />';
$svg .= '</svg>';

$image = SVG::fromString($svg);
$doc = $image->getDocument();

$rect = $doc->getChild(0);
$rect->setX(25)->setY(25);

header('Content-Type: image/svg+xml');
echo $image;
```

But I get this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function SVG\Reading\simplexml_load_string() in .../vendor/meyfa/php-svg/src/Reading/SVGReader.php:30
Stack trace:
#0 .../vendor/meyfa/php-svg/src/SVG.php(101): SVG\Reading\SVGReader->parseString()
#1 .../test_png.php(10): SVG\SVG::fromString()
#2 {main}
  thrown in .../vendor/meyfa/php-svg/src/Reading/SVGReader.php on line 30
```

php version:

    PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )

**Comment by meyfa** [comment]
Loading SVGs from string requires the PHP extension `SimpleXML`. Usually, this will be compiled into your version of PHP by default. If it is not, and you are on Linux, you might be able to install it via `apt install php-xml`. Specific commands and package names may differ for your distribution. Installing SimpleXML will fix the error.

There is unfortunately nothing we can do if you are unable to install this extension (e.g. on a hosted environment), except if we wrote our own XML parser, but that would be a ton of work.

**Comment by roipoussiere** [comment]
Ok, thanks for the clarification!

Maybe the readme could be updated to add some information about the php extensions, under the *Installation* section?

Something like:

> You may also want to install some php extensions:
> - **ext-gd** Needed to rasterize images;
> - **ext-simplexml** Needed to read SVG strings and files.

**Comment by meyfa** [comment]
@roipoussiere 
> Maybe the readme could be updated to add some information about the php extensions, under the _Installation_ section?

I completely agree. Issue #125 will track suggestions for improving the README.
