### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by meyfa** [meyfa/php-svg#125]
The README lacks a few things.

* The examples provide a good starting point but it might be worthwhile to add further notes on how this library works in general. E.g. that there are node classes, which types exist, how the whole constructing/loading - editing - outputting cycle works, etc.
* A summary of the currently supported feature set could help in understanding what this library can and cannot do. This avoids confusion when features that were expected of the library are actually still missing, and also serves as a guide for potential contributions.
* As mentioned in #123, it would be nice to include notes about required PHP extensions for certain features.
* Contributing section could be more welcoming (and provide actually useful hints instead of semi-important restrictions).
* Wording could be improved (the introductory part feels out of place as it is).

**Comment by roipoussiere** [comment]
In fact I think that the whole [setup wiki page](https://github.com/meyfa/php-svg/wiki/Setup) could be merged into the readme, because both pages are useful but contains duplicated information.

**Comment by meyfa** [comment]
I hope to get this done by the end of the month. It seems increasingly important as the project gains further traction.

**Comment by meyfa** [comment]
> In fact I think that the whole [setup wiki page](https://github.com/meyfa/php-svg/wiki/Setup) could be merged into the readme, because both pages are useful but contains duplicated information.

I went ahead and merged the entire wiki into the README, then deleted the wiki, since there was little additional value.
