### ISSUE TITLE
Parser error : internal error: Huge input lookup or Parser error : AttValue length too long

### ISSUE THREAD

**Issue by zaka221** [meyfa/php-svg#132]
Hello. Im trying open my SVG file (12mb) and I fail because is too big. Found solution in google 
$xml= simplexml_load_string($xml, 'SimpleXMLElement', LIBXML_COMPACT | LIBXML_PARSEHUGE),
but im not expert and i dont know how to edit your code to make it working. Can someone help me?
thanks you very much

**Comment by zaka221** [comment]
ok i solved problem 
just edit function 
    /**
     * Parses the given string as XML and turns it into an instance of SVG.
     * Returns null when parsing fails.
     *
     * @param string $string The XML string to parse.
     *
     * @return SVG|null An image object representing the parse result.
     */
    public function parseString($string)
    {
        //   $xml = simplexml_load_string($string, 'SimpleXMLElement', LIBXML_COMPACT | LIBXML_PARSEHUGE);
        $xml = new SimpleXMLElement($string, LIBXML_PARSEHUGE | LIBXML_NSCLEAN);

        return $this->parseXML($xml);
    }

**Comment by walidaalhomsi** [comment]
I created a pull request to solve this.
