### ISSUE TITLE
Question:how can it will shown with custom fonts

### ISSUE THREAD

**Issue by si812cn** [meyfa/php-svg#133]
I want to use php-svg to convert svg to png, but the display is not complete, some texts in custom fonts cannot be displayed

**Comment by si812cn** [comment]
$image = SVG::fromString($svg_str);

        $doc = $image->getDocument();

        // no filter
        $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Bold.otf');
        $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Medium.otf');
        $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Heavy.otf');
        $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Regular.otf');

        $rasterImage = $image->toRasterImage($doc->getWidth(), $doc->getHeight());
        header('Content-Type: image/png');
        imagepng($rasterImage);

**Comment by si812cn** [comment]
I had finished it.
$doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Bold.otf',null, 'blod');
    $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Medium.otf',null,'medium');
    $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Heavy.otf',null,'heavy');
    $doc->addFont(self::FONTS_DIR . 'SourceHanSansCN-Regular.otf','normal','normal');

**Comment by gregfr** [comment]
Greetings
I have the same problem, but the method `addFont()` doesn't exits... what can I do?
Regards
