### ISSUE TITLE
Fonts are not working on SVG 

### ISSUE THREAD

**Issue by tekkiwebsolutions** [meyfa/php-svg#168]
I'm using this library for one of my projects.
Font family name and weight has been implemented but fonts do not appear as per font family.
Check below function
  $svgNodes->addChild(
          (new SVGText($projectName, $textOffset, 129))
		
            ->setSize(85)
            ->setStyle('fill', $textColor)
            ->setStyle('font-family', $fontName)
            ->setStyle('font-weight', $fontWeight)
        );

Do I need to set font url. I'm creating a zip of images so how the font url will work here.
Thanks

**Comment by meyfa** [comment]
I've implemented a new system for registering fonts statically on the `SVG` class. The font to use for rendering is then automatically chosen as the best match. See PR #191 and please let me know what you think!
