### ISSUE TITLE
External fonts not working for text object

### ISSUE THREAD

**Issue by borjagarciab** [meyfa/php-svg#171]
Hi,
We seen that the system fonts works right, but when we want add an external font ,this is not working.
This is my code:

`<?php

require_once __DIR__ . '/vendor/autoload.php';

use SVG\SVG;
use SVG\Nodes\Structures\SVGFont;
use SVG\Nodes\Texts\SVGText;

$image = new SVG(100, 100);
$doc = $image->getDocument();

$fuente = new SVGFont('fontello', './fontello.ttf',true, "font/ttf" );

$texto = new SVGText("Hello World" , 10, 10);
$texto->setStyle('fill', '#FF00FF');
$texto = $texto->setFont($fuente);
$doc->addChild($texto);

header('Content-Type: image/svg+xml');
echo $image;`

**Comment by meyfa** [comment]
I've implemented a new system for registering fonts statically on the `SVG` class. The font to use for rendering is then automatically chosen as the best match. See PR #191 and please let me know what you think!
