### ISSUE TITLE
[feature request] generate sprite from an array of svg

### ISSUE THREAD

**Issue by peaceAndHodl** [meyfa/php-svg#174]
```
public static generateSvgSprite($svgArray = array(
                        "idForSvgDef" => 'filename.svg'
                       //, etc
                     )) {

    // ?

  return sanitizedSvgStringWithOneDefPerSvgInProvidedArray;
 }
```

**Comment by meyfa** [comment]
Thanks for your interest in PHP-SVG! Unfortunately, I think your request is out-of-scope for this library. Sprite sheets is specific enough that I think implementing it on the application side would be better. That said, this should be possible to implement on your own by building the document and adding the defs in a loop.

**Comment by peaceAndHodl** [comment]
ok no worries & thanks for the great lib anyway.

let's agree to disagree though : in my opinion sprite helps a lot in general, maybe a little more so with single page web app, but not so specifically  (to quote you) :

> Loading and parsing SVG images into document trees that are easy to modify and append.
