### ISSUE TITLE
Rasterizer doesn't render transparencies inside shapes

### ISSUE THREAD

**Issue by ricotheque** [meyfa/php-svg#28]
Tried rasterizing [this search icon SVG](https://upload.wikimedia.org/wikipedia/commons/8/8e/Feedbin-Icon-home-search.svg). Ended up with this:

![test](https://cloud.githubusercontent.com/assets/5687885/23646288/220e3e0a-034b-11e7-9acb-095a08afef43.png)

```php
require_once( __DIR__ . '/php-svg-master/autoloader.php' );

use SVG\SVG;

$svg = 'source.svg';
$test = SVG::fromFile( $svg );

$raster_image = $test->toRasterImage( 36, 36 );

imagepng( $raster_image, 'test.png', 9 );
imagejpeg( $raster_image, 'test.jpg', 100 );
```

Is this a limitation of the GD rendering library?

**Comment by JangoBrick** [comment]
Thanks for opening this issue, I'm looking into it.

**Comment by JangoBrick** [comment]
The problem seems to stem from the fact that the rasterizer treats every subpath as being completely unrelated to the previous ones, without taking into account that SVG imposes certain fill rules for cases where subpaths overlap.

I have no idea yet how to fix this, but it definitely needs attention.

Thanks again for reporting the problem!

**Comment by winkbrace** [comment]
Really unfortunate since this is quite an important requirement. It would have been so nice to be able to do this without phantom.js :/

**Comment by andykirk** [comment]
I came across this issue and though I'd post my solution to rendering the PNG, using Imagick:

```
// Save the SVG first:
// ($image is the SVG as per docs, $svg_filename is the path and name of file to output)
file_put_contents($svg_filename, $image->toXMLString());

// Create a new Imagick:
$im = new Imagick();
$im->readImageBlob(file_get_contents($svg_filename));

// This is for PNG24, but can be any output Imagick supports:
$im->setImageFormat("png24");

// $png_filename is the file path and name for resultant raster image:
$im->writeImage($png_filename);
$im->clear();
$im->destroy();
```

Hope that helps someone.

Cheers

**Comment by meyfa** [comment]
This will probably come as a surprise to everyone involved (myself included), but I finally implemented this. See PR #136.
The icon now renders just fine using the exact same code from above:

![search](https://user-images.githubusercontent.com/3982806/154801348-72276ccd-aba3-416d-b072-7dd79e1675dc.png)

I'd thank you for your patience, but I doubt this is still useful to any of the original participants of this discussion. Still it will hopefully benefit people that ran into this more recently!
