### ISSUE TITLE
xlink:href atrribute of image is not supported while parse svg

### ISSUE THREAD

**Issue by MukeshHome** [meyfa/php-svg#31]
Hi,
while parse svg file, xlink:href atrribute of image is not supported.

Thanks,
Mukesh

**Comment by MukeshHome** [comment]
Please do need full for above comment.

Here is code of svg : 

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="513" height="665" viewBox="0 0 513 665" xml:space="preserve">
<desc>Created with Fabric.js 1.7.13</desc>
<defs>
</defs>
<rect x="0" y="0" width="513" height="665" fill="#ffffff"></rect>
<g id="month" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;" transform="translate(0 332.5)" >
</g>
<rect id="box_1" x="-119" y="-150" rx="0" ry="0" width="238" height="300" style="stroke: rgb(0,0,0); stroke-width: 2; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(128,128,128); fill-rule: nonzero; opacity: 1;" transform="translate(135 173)"/>
<rect id="box_3" x="-119" y="-72.5" rx="0" ry="0" width="238" height="145" style="stroke: rgb(0,0,0); stroke-width: 2; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(128,128,128); fill-rule: nonzero; opacity: 1;" transform="translate(380 250.5)"/>
<rect id="box_2" x="-119" y="-72.5" rx="0" ry="0" width="238" height="145" style="stroke: rgb(0,0,0); stroke-width: 2; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(128,128,128); fill-rule: nonzero; opacity: 1;" transform="translate(380 95.5)"/>
<g transform="translate(374.69 97.5) scale(0.3 0.3)">
<image id="box_2_image" xlink:href="http://localhost/canvaschampindia/web/media//uploaded_images/2lji1u8h4pk6b8kmk5052qo1n6/27868_15053817441-_-_-0_test.jpg" x="-426" y="-240" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="852" height="480" preserveAspectRatio="none"></image>
</g>
<g transform="translate(376 256.13) scale(0.3 0.3)">
<image id="box_3_image" xlink:href="http://localhost/canvaschampindia/web/media//uploaded_images/2lji1u8h4pk6b8kmk5052qo1n6/5306_1505381764couple_with_parents_arm_in_arm_on_beach_smiling_portrait-_-_-0_test.jpg" x="-400" y="-266" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="800" height="532" preserveAspectRatio="none"></image>
</g>
<g transform="translate(229.48 171) scale(0.93 0.93)">
<image id="box_1_image" xlink:href="http://localhost/canvaschampindia/web/media//uploaded_images/2lji1u8h4pk6b8kmk5052qo1n6/4581_1505381757120604alumni24_small-_-_-0_test.jpg" x="-250" y="-162" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="324" preserveAspectRatio="none"></image>
</g>
<g transform="translate(257 332.5)">
<image xlink:href="http://localhost/canvaschampindia/web/skin/frontend/default/cptheme1/images/designtool/11x8.5.png" x="-257" y="-332.5" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="514" height="665" preserveAspectRatio="none"></image>
</g>
</svg>

**Comment by meyfa** [comment]
Hi, Mukesh.

That shouldn't be happening. Thanks for reporting the problem!
I will look into it and get back to you as soon as possible.

Thanks for your patience.

**Comment by meyfa** [comment]
I have pushed out a fix in commit 7e7415d. The fix will be in the next release.
