### ISSUE TITLE
SVGReader - Unknown tag are not retrieved

### ISSUE THREAD

**Issue by thomas-blackbird** [meyfa/php-svg#41]
Actually I know it's not a bug, but a feature.

`SVG\Reading\SVGReader::$nodeTypes` contain the allowed node types. However I'd like to read a SVG and retrieve all properties, even if there not implemented. There's a lot of elements: [SVG Elements](https://developer.mozilla.org/fr/docs/Web/SVG/Element) and it should impossible to implement all (hard work).

Otherwise it seems that the `SVGReader` class apply all properties as attributes to the parsed node. I understand that declaring specific node types is require in order to render the SVG, but In don't think so to read a SVG.
So, if the `SVGReader` do not find any concret class for the current parsed node, it should instantiate a new object. In order to instantiate the right node (`SVGNode` or `SVGNodeContainer` generic implementations), should we had a full associative array of elements (as key) with `boolean` (as value) which defined if an element is a container or a final node? 

If I'm totally wrong and it's not the purpose of the library, please tell me :)

**Comment by meyfa** [comment]
You are right, "unknown" nodes should not be discarded. I don't think differentiating between containers and non-containers is necessary — since we can never know for custom tags, it should always be an `SVGNodeContainer`.

**Comment by thomas-blackbird** [comment]
Actually I've noticed that it might have an issue. The library use `simplexml`, so the whole elements inside the tag are considered as children. So I understand why all nodes must be declared (it escape non elements to be casted as. eg: `<author>Lorem ipsum.</author>`).
But in other hand, in the case of the `text` element it be interesting to allows to retrieve the raw text.
Eg: `<text ...>Lorem ipsum.</text>`

I'm wondering if the solution could be:

- iterate all xml children (l.208 `SVGReader`)
- parse node (l.226 `SVGReader`)
-- xml name should be in list: (export [svg elements](https://developer.mozilla.org/fr/docs/Web/SVG/Element))
-- if in list: try to resolve specific node type object, else instantiate default `SVGNodeContainer`
-- if not in list: set child as `value` property in the `SVGNode`

Does it seems logic and compliant with the code design?

**Comment by meyfa** [comment]
This is now implemented in 5677a18. Nodes with an unknown tag name are retrieved in a generic implementation that supports everything supported by regular containers - i.e. attributes, styles, child nodes, and text content.
