### ISSUE TITLE
The Reader dismissed <linearGradient> label

### ISSUE THREAD

**Issue by AnthemiusGuo** [meyfa/php-svg#43]
When I read from an svg file, and show, I find the difference between the original file and the translate version from this lib.
the difference is :<linearGradient > not exists now in the read from file of this lib version......

**Comment by meyfa** [comment]
Thanks for reporting this. It is a known problem and already tracked in issue #41. I will close this as duplicate, but there will be a fix for this soon. If you want to add anything, please head over to #41.
