### ISSUE TITLE
How to output and save 

### ISSUE THREAD

**Issue by audas** [meyfa/php-svg#63]
Sorry if already addressed but am not sure of the correct way to output svg to file ?

**Comment by meyfa** [comment]
I'm assuming you've already got an `SVG` object (an image) loaded from somewhere or constructed one manually.

You can use its `toXMLString()` method to obtain the SVG in text form, and then write that out whichever way you prefer. The simplest way would be using PHP's [`file_put_contents`](http://php.net/manual/en/function.file-put-contents.php).

Complete example:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use SVG\SVG;
use SVG\Nodes\Shapes\SVGRect;

// image with 100x100 viewport
$image = new SVG(100, 100);
$doc = $image->getDocument();

// blue 40x40 square at (0, 0)
$square = new SVGRect(0, 0, 40, 40);
$square->setStyle('fill', '#0000FF');
$doc->addChild($square);

// obtain the SVG text
$svgString = $image->toXMLString();

// write it to a file
file_put_contents('path/to/the-file.svg', $svgString);
```

I hope this solved your problem. Please, always ask if something is unclear!

**Comment by meyfa** [comment]
I'm closing this issue under the assumption that it has been solved. Please reopen it if I'm wrong.
