### ISSUE TITLE
Mark "ext-gd" extension as optional

### ISSUE THREAD

**Issue by m-ober** [meyfa/php-svg#76]
As the gd extension seems only required to rasterize image, it would be nice to mark it as optional in the `composer.json`, e.g.:

```
    "suggest": {
        "ext-gd": "Needed to rasterize images"
    }
```

**Comment by meyfa** [comment]
This seems like a good idea, thanks for the suggestion! Will take care of it.

**Comment by meyfa** [comment]
I'll mark simplexml as optional too, since not everyone needs parsing, either.

**Comment by meyfa** [comment]
Done in b72a174dbed867642e4b2ac37eb1ebf6705c4b04.
