### ISSUE TITLE
Any way to re-use an embedded font?

### ISSUE THREAD

**Issue by kapil-ancora** [meyfa/php-svg#79]
I generate an SVG from a template by rendering some text in it. To render the text, I embed a font in the svg. Now I want to use this svg-with-text as a template and add some more text to it, using the font I have already embedded in the svg. Is there a clean way to do it with this library?

**Comment by kapil-ancora** [comment]
nevermind, found out, i can just use `setStyle`

**Comment by notflip** [comment]
@kapil-ancora Can you share the code you used to achieve this? I can't seem to load custom fonts
