### ISSUE TITLE
How to set fonts for rasterization on existing documents?

### ISSUE THREAD

**Issue by JukkaHau** [meyfa/php-svg#82]
when rasterizing svg, all the texts are missing in the png file.
is it implemented at all to rasterize texts ?

sorry, was just missing a font. 
You can delete this issue.
works with this, ->setFont(new SVGFont('arial', './arial.ttf'))

**Comment by r3sist** [comment]
Dear Developers and Users,
I have the similar problem and I couldn't figure how to use `setFont()` from *outside*.

How can I inject my font name (and location on server) into `$params['font_path']`? 

My texts have `font-family` attribute in original SVG `$svg` source:

```php
$image = \SVG\SVG::fromString($svg);
$doc = $image->getDocument();
$rasterImage = $image->toRasterImage($doc->getWidth(), $doc->getHeight());
ob_start();
imagepng($rasterImage);
$string=  ob_get_clean();
```

Do you have any suggestions?
Thank you for reading!

**Comment by notflip** [comment]
Is it possible, using this plugin to create a rasterized image from an SVG that has text?

**Comment by notflip** [comment]
@r3sist Did you find a solution to this? Is it at all possible to use custom fonts with this library?

**Comment by r3sist** [comment]
@notflip No, sorry. I switched to _Imagick_ with _inkscape_ engine for rasterization process. Inkscape is important for SVG font rendering. It also handles rotated texts.

```
$image = new Imagick();
$image->setFont(__DIR__ . '/Sans-Serif.ttf');
$image->readImageBlob($svg);
$image->setImageFormat('png');
$image->getImageBlob()
```

**Comment by notflip** [comment]
I was using Imagick as well for rendering the image! Did not know about the setFont() method, with this, do you now have a working png generator with fonts? Did you have to any special settings to Imagick? Thanks!

**Comment by r3sist** [comment]
Yes I have a working project. [Comparison example](https://ln.sync.com/dl/7bd8c3010/yrzisch7-gp6guke8-mev689wt-5sjnkyaj) - SVG left

As far as I know, Imagick will use automatically Inkscape if it's installed. 

In my project notes I found (for Ubuntua 20.04):

> Imagick `readImageBlob()` needs:
> 
> ```
> apt-get install ghostscript
> 
> apt-get install libgraphicsmagick1-dev libmagickcore-dev libmagickcore-6.q16-2 libmagickcore-6.q16-2-extr
> ```
> 
> Replace built-in SVG processor with *inkscape*:
> 
> ```
> apt-get install inkscape
> ```

**Comment by notflip** [comment]
Thanks! This is of great help, the only thing I don't get is if you define the font with setFont in Imagick, do you still need to set the font using this library's methods for doing that, for example

```
$text = (new SVGText('Hello World', '50%', '50%'))
    ->setFont(new SVGFont('Montserrat-ExtraBoldItalic', $fontPath));
```

**Comment by r3sist** [comment]
I think you should test it. I have font attrinbutes in raw SVG, so I guess yes. However I use only generic CSS font types like *Sans-Serif* (`font-family="Sans-Serif"`) and I have a .ttf file called like this. (Disclamier: I don't always use this lib for generating SVG)

**Comment by meyfa** [comment]
I've implemented a new system for registering fonts statically on the `SVG` class. The font to use for rendering is then automatically chosen as the best match. See PR #191 and please let me know what you think!
