### ISSUE TITLE
How do I draw a line?

### ISSUE THREAD

**Issue by Zorgios** [meyfa/php-svg#84]
Sorry for my stupid question.

How do I draw a line? It is the "line" element

**Comment by SridharRamasami** [comment]
$obj = new SVGLine(11, 12, 13, 14);  //  x1, y1, x2, y2

From here:
https://github.com/meyfa/php-svg/blob/master/tests/Nodes/Shapes/SVGLineTest.php

**Comment by meyfa** [comment]
This is correct. You can adapt the example from the README, like this:

```php
<?php

use SVG\SVG;
use SVG\Nodes\Shapes\SVGLine;

// create a 100x100 image
$image = new SVG(100, 100);
$doc = $image->getDocument();

// add a line
$line = new SVGLine(0, 0, 20, 40); // startX, startY, endX, endY
$line->setStyle('stroke', 'red');
$doc->addChild($line);

// output the SVG file
header('Content-Type: image/svg+xml');
echo $image;
```

There is a class for every SVG element. Browse https://github.com/meyfa/php-svg/tree/master/src/Nodes/Shapes for the shape elements, and the other directories for other types of elements.
